 <!--  Adapted from code generated by ChatGPT:https://chatgpt.com/share/67890672-16d4-8007-a30f-19d18c37df6b -->
    
<x-admin-layout>
    <x-slot name="header">
        <h2 class="text-2xl font-bold text-BLACK">
            {{ __('Manage Users') }}
        </h2>
    </x-slot>


 <!-- Search and Filter Section -->
 <div class="my-4 flex items-center space-x-4">
    <form action="{{ route('admin.index') }}" method="GET" class="flex items-center space-x-2">
        <input type="text" name="search" placeholder="Search by name/email" class="px-4 py-2 w-80 rounded-lg shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 border-gray-300">
        <button type="submit" class="px-4 py-2 bg-indigo-600 text-white rounded-lg shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
            Search
        </button>
    </form>
    <span></span> 
    <form action="{{ route('admin.index') }}" method="GET" class="flex items-center space-x-2">
        <select name="role" class="px-4 py-2 w-48 rounded-lg shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 border-gray-300">
            <option value="">Filter by Role</option>
            <option value="admin">Admin</option>
            <option value="user">User</option>
        </select>
        <button type="submit" class="px-4 py-2 bg-indigo-600 text-white rounded-lg shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
            Filter
        </button>
    </form>
</div>

    <!-- Users Table -->
    <div class="bg-slate-900 rounded-lg shadow-lg overflow-hidden">
        <table class="w-full">
            <thead>
                <tr>
                    <th class="px-6 py-4 bg-slate-800 text-left">
                        <span class="text-sm font-semibold text-slate-300 uppercase tracking-wider">Name</span>
                    </th>
                    <th class="px-6 py-4 bg-slate-800 text-left">
                        <span class="text-sm font-semibold text-slate-300 uppercase tracking-wider">Email</span>
                    </th>
                    <th class="px-6 py-4 bg-slate-800 text-left">
                        <span class="text-sm font-semibold text-slate-300 uppercase tracking-wider">Role</span>
                    </th>
                    <th class="px-6 py-4 bg-slate-800"></th>
                </tr>
            </thead>
            <tbody class="divide-y divide-slate-700">
                @foreach($users as $user)
                    <tr class="hover:bg-slate-800/50 transition-colors">
                        <td class="px-6 py-4 whitespace-nowrap text-slate-200">{{ $user->name }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-slate-200">{{ $user->email }}</td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <span class="{{ $user->is_admin ? 'bg-indigo-600' : 'bg-red-600' }} px-3 py-1 rounded-full text-sm text-white">
                                {{ $user->is_admin ? 'Admin' : 'User' }}
                            </span>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right">
                            <form action="{{ route('admin.toggle-admin', $user) }}" method="POST">
                                @csrf
                                <button type="submit" 
                                    class="inline-flex items-center px-4 py-2 rounded-md text-sm font-medium {{ $user->is_admin ? 'bg-red-600 hover:bg-red-700' : 'bg-indigo-600 hover:bg-indigo-700' }} text-white transition-colors duration-200">
                                    {{ $user->is_admin ? 'Remove Admin' : 'Make Admin' }}
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</x-admin-layout>